// This file is auto-generated by GitHub Actions.
// Do NOT edit manually — your changes will be overwritten on next push.
// To update credentials: GitHub repo → Settings → Secrets and variables → Actions
const _SUPA_URL = 'PLACEHOLDER';
const _SUPA_KEY = 'PLACEHOLDER';
